name: ios_build
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.1
  firebaseapis: ^0.1.2
  googleapis_auth: ^1.3.1
  http: ^0.13.4
  json_annotation: ^4.5.0

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  surf_lint_rules: ^1.5.0
