
dart_code_metrics:
  metrics-exclude:
    - lib/generated/**
    - '**generated/**'
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
    number-of-methods: 10
    weight-of-class: 0.33
    maintainability-index: 50

linter:
  rules:
    public_member_api_docs: true

analyzer:
  exclude: [ lib/generated/**, '**/*.g.dart', '**generated**', '**/*.gr.dart', script/** ]
