name: test_task_rickandmorty
version: "0.0.1-dev.0"
description: a Flutter template project for development.
publish_to: none

dependencies:
  auto_route: ^5.0.4
  cached_network_image: 3.2.3
  character_card:
    path: ./features/character_card
  character_page:
    path: ./features/character_page
  common:
    path: ./features/common
  dio: ^4.0.6
  elementary: ^2.0.0
  favorite:
    path: ./features/favorite
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  logger: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  main_page:
    path: ./features/main_page
  modal_bottom_sheet: ^2.1.2

  navigation:
    path: ./features/navigation
  provider: ^6.0.5
  retrofit: ^3.3.1
  share_plus: ^6.3.4
  super_sliver_list: 0.0.7
  surf_logger: ^1.1.0

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.5.1
  elementary_test: ^1.1.3
  flutter_driver:
    sdk: flutter
  flutter_gherkin: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.10
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  quick_actions: ^1.0.1
  retrofit_generator: ^4.2.0

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icons/icon_ios.png"
  image_path_android: "assets/icons/icon_android.png"
  adaptive_icon_background: "assets/icons/background.png"
  adaptive_icon_foreground: "assets/icons/foreground.png"

flutter_intl:
  enabled: false
  class_name: AppLocalizations
  main_locale: ru

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash_screen/splash_foreground.png
  fullscreen: true
